parameters:
  param1: param1_value
  param2: param2_value
  env_name: base_env
  secret_name: secret1
config:
  keyring:
    service_name: "{PARAM: env_name}_secrets"
secrets:
  secret1:
    keyring_name: demo_secret1
    local: True         # local only secret is stored in keyring only
env:
  var1: var1
  var2: "{PARAM: param1} - {PARAM: param2}"
  secret_var: "{SECRET: secret1}"
  dynamic_secret_var: "{SECRET: {PARAM: secret_name}}"